# Generated by Django 4.1.4 on 2023-04-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.CharField(default=3, max_length=30),
        ),
    ]
