# Generated by Django 5.0.2 on 2024-04-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_booking_room_booking_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_mode',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
