name: Access server
on: push
jobs:
  access_server:
    name: Access server
    runs-on: ubuntu-latest
    steps:
      - name: Create a file
        uses: appleboy/ssh-action@master
        with:
          host: 3.111.144.91
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: echo hello 1world > hello.txt
